#!/usr/bin/env python3
"""Generate css/tokens.css from tools/tokens.json (the Crisp Design System tokens)."""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FONT_STACK = '"Schibsted Grotesk", system-ui, -apple-system, "Segoe UI", Arial, sans-serif'


def resolve(value, colours):
    """Resolve '{alias}' colour values to the colour they point at."""
    m = re.fullmatch(r"\{([\w-]+)\}", value)
    return resolve(colours[m.group(1)], colours) if m else value


def main():
    data = json.loads((ROOT / "tools" / "tokens.json").read_text(encoding="utf-8"))
    colours = {t["name"]: t["value"] for t in data["color"]["tokens"]}

    root = [f"  --font-sans: {FONT_STACK};"]
    root += [f"  --{n}: {resolve(v, colours)};" for n, v in colours.items()]
    for group in ("spacing", "radius", "layout", "padding", "gap", "shadow"):
        root += [f"  --{t['name']}: {t['value']};" for t in data[group]["tokens"]]

    desktop, mobile = [], []
    for g in data["type"]["groups"]:
        for s in g["styles"]:
            name = s["name"]
            target, base = (mobile, name[:-2]) if name.endswith("-m") else (desktop, name)
            target.append(f"  --fs-{base}: {s['fontSize']};")
            target.append(f"  --lh-{base}: {s['lineHeight']};")
            if not name.endswith("-m"):
                desktop.append(f"  --fw-{base}: {s['fontWeight']};")
                desktop.append(f"  --ls-{base}: {s['letterSpacing']};")

    css = (
        "/* Generated by tools/tokens_to_css.py from tools/tokens.json. Do not edit. */\n"
        ":root {\n" + "\n".join(root + desktop) + "\n}\n\n"
        "@media (max-width:599px) {\n  :root {\n" + "\n".join("  " + l for l in mobile) + "\n  }\n}\n"
    )
    (ROOT / "css" / "tokens.css").write_text(css, encoding="utf-8")
    print(f"wrote css/tokens.css ({len(root) + len(desktop)} desktop vars, {len(mobile)} mobile overrides)")


if __name__ == "__main__":
    main()
